import 'package:flutter/material.dart';

import 'team.dart';

/// Base de données des sélections nationales jouables. La Mauritanie est
/// toujours en première position (équipe par défaut de toute l'application).
class TeamsDatabase {
  static const List<Team> all = [
    // ─────────────── Afrique (CAF) ───────────────
    Team(
      id: 'mru', name: 'Mauritanie', nameEn: 'Mauritania',
      continent: Continent.africa, confederation: 'CAF',
      flag: '🇲🇷', fifaCode: 'MRT',
      colors: [Color(0xFF00A651), Color(0xFFFFD700), Color(0xFFD21034)],
      attack: 72, midfield: 71, defense: 74, goalkeeper: 73,
      speed: 70, passing: 71, shooting: 70,
    ),
    Team(
      id: 'mar', name: 'Maroc', nameEn: 'Morocco',
      continent: Continent.africa, confederation: 'CAF',
      flag: '🇲🇦', fifaCode: 'MAR',
      colors: [Color(0xFFC1272D), Color(0xFF006233)],
      attack: 84, midfield: 82, defense: 86, goalkeeper: 85,
      speed: 83, passing: 84, shooting: 83,
    ),
    Team(
      id: 'dza', name: 'Algérie', nameEn: 'Algeria',
      continent: Continent.africa, confederation: 'CAF',
      flag: '🇩🇿', fifaCode: 'ALG',
      colors: [Color(0xFF006233), Color(0xFFFFFFFF), Color(0xFFD21034)],
      attack: 80, midfield: 79, defense: 78, goalkeeper: 79,
      speed: 82, passing: 80, shooting: 79,
    ),
    Team(
      id: 'tun', name: 'Tunisie', nameEn: 'Tunisia',
      continent: Continent.africa, confederation: 'CAF',
      flag: '🇹🇳', fifaCode: 'TUN',
      colors: [Color(0xFFE70013), Color(0xFFFFFFFF)],
      attack: 76, midfield: 75, defense: 77, goalkeeper: 76,
      speed: 74, passing: 75, shooting: 74,
    ),
    Team(
      id: 'egy', name: 'Égypte', nameEn: 'Egypt',
      continent: Continent.africa, confederation: 'CAF',
      flag: '🇪🇬', fifaCode: 'EGY',
      colors: [Color(0xFFCE1126), Color(0xFFFFFFFF), Color(0xFF000000)],
      attack: 78, midfield: 77, defense: 76, goalkeeper: 80,
      speed: 76, passing: 77, shooting: 78,
    ),
    Team(
      id: 'sen', name: 'Sénégal', nameEn: 'Senegal',
      continent: Continent.africa, confederation: 'CAF',
      flag: '🇸🇳', fifaCode: 'SEN',
      colors: [Color(0xFF00853F), Color(0xFFFDEF42), Color(0xFFE31B23)],
      attack: 83, midfield: 80, defense: 82, goalkeeper: 83,
      speed: 84, passing: 79, shooting: 82,
    ),
    Team(
      id: 'civ', name: "Côte d'Ivoire", nameEn: 'Ivory Coast',
      continent: Continent.africa, confederation: 'CAF',
      flag: '🇨🇮', fifaCode: 'CIV',
      colors: [Color(0xFFFF8200), Color(0xFFFFFFFF), Color(0xFF009A44)],
      attack: 81, midfield: 79, defense: 78, goalkeeper: 78,
      speed: 83, passing: 78, shooting: 80,
    ),
    Team(
      id: 'cmr', name: 'Cameroun', nameEn: 'Cameroon',
      continent: Continent.africa, confederation: 'CAF',
      flag: '🇨🇲', fifaCode: 'CMR',
      colors: [Color(0xFF007A5E), Color(0xFFCE1126), Color(0xFFFCD116)],
      attack: 79, midfield: 77, defense: 77, goalkeeper: 77,
      speed: 81, passing: 76, shooting: 78,
    ),
    Team(
      id: 'nga', name: 'Nigeria', nameEn: 'Nigeria',
      continent: Continent.africa, confederation: 'CAF',
      flag: '🇳🇬', fifaCode: 'NGA',
      colors: [Color(0xFF008751), Color(0xFFFFFFFF)],
      attack: 82, midfield: 80, defense: 79, goalkeeper: 78,
      speed: 85, passing: 78, shooting: 81,
    ),
    Team(
      id: 'gha', name: 'Ghana', nameEn: 'Ghana',
      continent: Continent.africa, confederation: 'CAF',
      flag: '🇬🇭', fifaCode: 'GHA',
      colors: [Color(0xFFCE1126), Color(0xFFFCD116), Color(0xFF006B3F)],
      attack: 78, midfield: 77, defense: 76, goalkeeper: 76,
      speed: 80, passing: 76, shooting: 77,
    ),
    Team(
      id: 'rsa', name: 'Afrique du Sud', nameEn: 'South Africa',
      continent: Continent.africa, confederation: 'CAF',
      flag: '🇿🇦', fifaCode: 'RSA',
      colors: [Color(0xFF007749), Color(0xFFFFB612), Color(0xFF000000)],
      attack: 74, midfield: 73, defense: 74, goalkeeper: 75,
      speed: 75, passing: 73, shooting: 73,
    ),
    Team(
      id: 'mli', name: 'Mali', nameEn: 'Mali',
      continent: Continent.africa, confederation: 'CAF',
      flag: '🇲🇱', fifaCode: 'MLI',
      colors: [Color(0xFF14B53A), Color(0xFFFCD116), Color(0xFFCE1126)],
      attack: 77, midfield: 76, defense: 77, goalkeeper: 76,
      speed: 78, passing: 75, shooting: 76,
    ),

    // ─────────────── Europe (UEFA) ───────────────
    Team(
      id: 'fra', name: 'France', nameEn: 'France',
      continent: Continent.europe, confederation: 'UEFA',
      flag: '🇫🇷', fifaCode: 'FRA',
      colors: [Color(0xFF0055A4), Color(0xFFFFFFFF), Color(0xFFEF4135)],
      attack: 91, midfield: 89, defense: 88, goalkeeper: 89,
      speed: 90, passing: 90, shooting: 91,
    ),
    Team(
      id: 'esp', name: 'Espagne', nameEn: 'Spain',
      continent: Continent.europe, confederation: 'UEFA',
      flag: '🇪🇸', fifaCode: 'ESP',
      colors: [Color(0xFFC60B1E), Color(0xFFFFC400)],
      attack: 87, midfield: 90, defense: 85, goalkeeper: 86,
      speed: 84, passing: 92, shooting: 86,
    ),
    Team(
      id: 'por', name: 'Portugal', nameEn: 'Portugal',
      continent: Continent.europe, confederation: 'UEFA',
      flag: '🇵🇹', fifaCode: 'POR',
      colors: [Color(0xFF006600), Color(0xFFFF0000)],
      attack: 89, midfield: 87, defense: 85, goalkeeper: 87,
      speed: 87, passing: 88, shooting: 90,
    ),
    Team(
      id: 'eng', name: 'Angleterre', nameEn: 'England',
      continent: Continent.europe, confederation: 'UEFA',
      flag: '🏴', fifaCode: 'ENG',
      colors: [Color(0xFFFFFFFF), Color(0xFFCE1124)],
      attack: 88, midfield: 86, defense: 87, goalkeeper: 86,
      speed: 89, passing: 87, shooting: 88,
    ),
    Team(
      id: 'ita', name: 'Italie', nameEn: 'Italy',
      continent: Continent.europe, confederation: 'UEFA',
      flag: '🇮🇹', fifaCode: 'ITA',
      colors: [Color(0xFF0066CC), Color(0xFFFFFFFF), Color(0xFF009246)],
      attack: 85, midfield: 86, defense: 87, goalkeeper: 85,
      speed: 83, passing: 87, shooting: 84,
    ),
    Team(
      id: 'ger', name: 'Allemagne', nameEn: 'Germany',
      continent: Continent.europe, confederation: 'UEFA',
      flag: '🇩🇪', fifaCode: 'GER',
      colors: [Color(0xFF000000), Color(0xFFDD0000), Color(0xFFFFCE00)],
      attack: 87, midfield: 86, defense: 85, goalkeeper: 86,
      speed: 85, passing: 88, shooting: 87,
    ),
    Team(
      id: 'bel', name: 'Belgique', nameEn: 'Belgium',
      continent: Continent.europe, confederation: 'UEFA',
      flag: '🇧🇪', fifaCode: 'BEL',
      colors: [Color(0xFF000000), Color(0xFFFDDA24), Color(0xFFEF3340)],
      attack: 86, midfield: 85, defense: 83, goalkeeper: 84,
      speed: 84, passing: 86, shooting: 86,
    ),
    Team(
      id: 'ned', name: 'Pays-Bas', nameEn: 'Netherlands',
      continent: Continent.europe, confederation: 'UEFA',
      flag: '🇳🇱', fifaCode: 'NED',
      colors: [Color(0xFFFF7900), Color(0xFFFFFFFF), Color(0xFF21468B)],
      attack: 85, midfield: 84, defense: 83, goalkeeper: 85,
      speed: 85, passing: 85, shooting: 85,
    ),
    Team(
      id: 'cro', name: 'Croatie', nameEn: 'Croatia',
      continent: Continent.europe, confederation: 'UEFA',
      flag: '🇭🇷', fifaCode: 'CRO',
      colors: [Color(0xFFFF0000), Color(0xFFFFFFFF), Color(0xFF171796)],
      attack: 82, midfield: 85, defense: 80, goalkeeper: 83,
      speed: 80, passing: 86, shooting: 81,
    ),
    Team(
      id: 'sui', name: 'Suisse', nameEn: 'Switzerland',
      continent: Continent.europe, confederation: 'UEFA',
      flag: '🇨🇭', fifaCode: 'SUI',
      colors: [Color(0xFFFF0000), Color(0xFFFFFFFF)],
      attack: 79, midfield: 80, defense: 81, goalkeeper: 82,
      speed: 79, passing: 81, shooting: 78,
    ),

    // ─────────────── Amérique du Sud (CONMEBOL) ───────────────
    Team(
      id: 'arg', name: 'Argentine', nameEn: 'Argentina',
      continent: Continent.southAmerica, confederation: 'CONMEBOL',
      flag: '🇦🇷', fifaCode: 'ARG',
      colors: [Color(0xFF75AADB), Color(0xFFFFFFFF)],
      attack: 90, midfield: 89, defense: 86, goalkeeper: 90,
      speed: 88, passing: 89, shooting: 91,
    ),
    Team(
      id: 'bra', name: 'Brésil', nameEn: 'Brazil',
      continent: Continent.southAmerica, confederation: 'CONMEBOL',
      flag: '🇧🇷', fifaCode: 'BRA',
      colors: [Color(0xFFFFDF00), Color(0xFF009739), Color(0xFF012169)],
      attack: 90, midfield: 88, defense: 85, goalkeeper: 85,
      speed: 91, passing: 88, shooting: 89,
    ),
    Team(
      id: 'uru', name: 'Uruguay', nameEn: 'Uruguay',
      continent: Continent.southAmerica, confederation: 'CONMEBOL',
      flag: '🇺🇾', fifaCode: 'URU',
      colors: [Color(0xFF7FB3E8), Color(0xFFFFFFFF)],
      attack: 84, midfield: 81, defense: 85, goalkeeper: 84,
      speed: 80, passing: 80, shooting: 84,
    ),
    Team(
      id: 'col', name: 'Colombie', nameEn: 'Colombia',
      continent: Continent.southAmerica, confederation: 'CONMEBOL',
      flag: '🇨🇴', fifaCode: 'COL',
      colors: [Color(0xFFFCD116), Color(0xFF003893), Color(0xFFCE1126)],
      attack: 83, midfield: 81, defense: 79, goalkeeper: 80,
      speed: 85, passing: 80, shooting: 82,
    ),
    Team(
      id: 'chi', name: 'Chili', nameEn: 'Chile',
      continent: Continent.southAmerica, confederation: 'CONMEBOL',
      flag: '🇨🇱', fifaCode: 'CHI',
      colors: [Color(0xFFD52B1E), Color(0xFFFFFFFF), Color(0xFF0039A6)],
      attack: 78, midfield: 78, defense: 77, goalkeeper: 77,
      speed: 77, passing: 78, shooting: 78,
    ),
    Team(
      id: 'per', name: 'Pérou', nameEn: 'Peru',
      continent: Continent.southAmerica, confederation: 'CONMEBOL',
      flag: '🇵🇪', fifaCode: 'PER',
      colors: [Color(0xFFD91023), Color(0xFFFFFFFF)],
      attack: 76, midfield: 75, defense: 76, goalkeeper: 75,
      speed: 74, passing: 75, shooting: 74,
    ),

    // ─────────────── Amérique du Nord (CONCACAF) ───────────────
    Team(
      id: 'usa', name: 'États-Unis', nameEn: 'United States',
      continent: Continent.northAmerica, confederation: 'CONCACAF',
      flag: '🇺🇸', fifaCode: 'USA',
      colors: [Color(0xFF3C3B6E), Color(0xFFFFFFFF), Color(0xFFB22234)],
      attack: 79, midfield: 78, defense: 79, goalkeeper: 78,
      speed: 82, passing: 77, shooting: 78,
    ),
    Team(
      id: 'mex', name: 'Mexique', nameEn: 'Mexico',
      continent: Continent.northAmerica, confederation: 'CONCACAF',
      flag: '🇲🇽', fifaCode: 'MEX',
      colors: [Color(0xFF006847), Color(0xFFFFFFFF), Color(0xFFCE1126)],
      attack: 80, midfield: 79, defense: 78, goalkeeper: 79,
      speed: 81, passing: 79, shooting: 79,
    ),
    Team(
      id: 'can', name: 'Canada', nameEn: 'Canada',
      continent: Continent.northAmerica, confederation: 'CONCACAF',
      flag: '🇨🇦', fifaCode: 'CAN',
      colors: [Color(0xFFFF0000), Color(0xFFFFFFFF)],
      attack: 79, midfield: 77, defense: 76, goalkeeper: 76,
      speed: 84, passing: 75, shooting: 78,
    ),
    Team(
      id: 'crc', name: 'Costa Rica', nameEn: 'Costa Rica',
      continent: Continent.northAmerica, confederation: 'CONCACAF',
      flag: '🇨🇷', fifaCode: 'CRC',
      colors: [Color(0xFFCE1126), Color(0xFFFFFFFF), Color(0xFF002B7F)],
      attack: 74, midfield: 73, defense: 75, goalkeeper: 75,
      speed: 75, passing: 73, shooting: 73,
    ),

    // ─────────────── Asie (AFC) ───────────────
    Team(
      id: 'jpn', name: 'Japon', nameEn: 'Japan',
      continent: Continent.asia, confederation: 'AFC',
      flag: '🇯🇵', fifaCode: 'JPN',
      colors: [Color(0xFF002B7F), Color(0xFFFFFFFF), Color(0xFFBC002D)],
      attack: 81, midfield: 83, defense: 80, goalkeeper: 80,
      speed: 80, passing: 85, shooting: 80,
    ),
    Team(
      id: 'kor', name: 'Corée du Sud', nameEn: 'South Korea',
      continent: Continent.asia, confederation: 'AFC',
      flag: '🇰🇷', fifaCode: 'KOR',
      colors: [Color(0xFFCD2E3A), Color(0xFFFFFFFF), Color(0xFF0047A0)],
      attack: 80, midfield: 79, defense: 78, goalkeeper: 78,
      speed: 84, passing: 78, shooting: 80,
    ),
    Team(
      id: 'ksa', name: 'Arabie Saoudite', nameEn: 'Saudi Arabia',
      continent: Continent.asia, confederation: 'AFC',
      flag: '🇸🇦', fifaCode: 'KSA',
      colors: [Color(0xFF006C35), Color(0xFFFFFFFF)],
      attack: 75, midfield: 75, defense: 76, goalkeeper: 76,
      speed: 74, passing: 75, shooting: 74,
    ),
    Team(
      id: 'qat', name: 'Qatar', nameEn: 'Qatar',
      continent: Continent.asia, confederation: 'AFC',
      flag: '🇶🇦', fifaCode: 'QAT',
      colors: [Color(0xFF8D1B3D), Color(0xFFFFFFFF)],
      attack: 73, midfield: 74, defense: 75, goalkeeper: 76,
      speed: 72, passing: 74, shooting: 72,
    ),
    Team(
      id: 'irn', name: 'Iran', nameEn: 'Iran',
      continent: Continent.asia, confederation: 'AFC',
      flag: '🇮🇷', fifaCode: 'IRN',
      colors: [Color(0xFF239F40), Color(0xFFFFFFFF), Color(0xFFDA0000)],
      attack: 77, midfield: 76, defense: 79, goalkeeper: 79,
      speed: 75, passing: 75, shooting: 76,
    ),

    // ─────────────── Océanie ───────────────
    Team(
      id: 'aus', name: 'Australie', nameEn: 'Australia',
      continent: Continent.oceania, confederation: 'AFC',
      flag: '🇦🇺', fifaCode: 'AUS',
      colors: [Color(0xFFFFCD00), Color(0xFF00843D)],
      attack: 76, midfield: 75, defense: 77, goalkeeper: 77,
      speed: 76, passing: 75, shooting: 75,
    ),
    Team(
      id: 'nzl', name: 'Nouvelle-Zélande', nameEn: 'New Zealand',
      continent: Continent.oceania, confederation: 'OFC',
      flag: '🇳🇿', fifaCode: 'NZL',
      colors: [Color(0xFF000000), Color(0xFFFFFFFF)],
      attack: 70, midfield: 69, defense: 71, goalkeeper: 71,
      speed: 70, passing: 68, shooting: 68,
    ),
  ];

  static Team get defaultTeam => all.first; // Mauritanie

  static Team byId(String id) => all.firstWhere((t) => t.id == id, orElse: () => defaultTeam);

  static List<Team> byContinent(Continent continent) =>
      all.where((t) => t.continent == continent).toList();
}
